---
- hosts: all

  roles:
    - homebrew

  tasks:
    - homebrew: name=macvim install_options=override-system-vim
    - homebrew: name='{{ item }}' update_homebrew=no state=present
      with_items:
        - bash-completion
        - git
        - tmux
        - htop
        - reattach-to-user-namespace
        - bzr
        - hg
        - ctags
        - node
        - mongodb
        - mysql
        - redis
        - ssh-copy-id
        - proctools
        - gnu-sed
        - docker
        - tig
        - awscli
        - chruby
        - ruby-install
        - coreutils
        - maven
        - gradle
        - postgresql
        - macvim

    - homebrew_cask: name='{{ item }}' state=present
      with_items:
        - alfred
        - spotify
        - google-chrome
        - iterm2
        - java
        - virtualbox
        - vagrant
        - slack
        - harvest
        - vmware-fusion
        - skitch
        - google-hangouts
        - valentina-studio
        - pgadmin3
        - transmission
        - daisydisk
        - vagrant-manager
        - skype
        - keka
      tags: cask
