---

- name: Make sure Homebrew directory exists
  file: 
    path=/usr/local
    state=directory
    mode=0775
    group=admin
  sudo: yes

- stat: path=/usr/local/bin/brew
  register: brew_executable
- name: Install Homebrew with install script
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not brew_executable.stat.exists

